#### Import NumPy

In [ ]:
import numpy as np

#### Create an array of 10 zeros

Made array of zeroes using numpy function

In [ ]:
zero = np.zeros(10)

#### Create an array of 10 ones

In [ ]:
one = np.ones(10)

#### Create an array of 10 fives

In [ ]:
five = np.full(10,5)

#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
array1 = np.arange(10, 51)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
even = np.arange(10, 51,2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
identity_matrix = np.identity(3)

#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
random_number = np.random.rand()

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
random_numbers = np.random.normal(0, 1, 25)

#### Create the following matrix: -!del!-

In [ ]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
linear_space = np.linspace(0, 1, 20)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
your_array = np.array([[12, 13, 14, 15],
                       [17, 18, 19, 20],
                       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
x = 20
x

20

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
array2 = np.array([[2],
                       [7],
                       [12]])
array2

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
np.array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat = np.array([[20, 21, 22, 23],
                [25, 26, 27, 28],
                [30, 31, 32, 33]])

sum_of_values = np.sum(mat)

print(sum_of_values)

318


#### Get the standard deviation of the values in mat

In [ ]:
mat = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])
std_deviation = np.std(mat)

print(std_deviation)

7.2111025509279782

#### Get the sum of all the columns in mat

In [ ]:



mat = np.array([[12, 13, 14, 15],
                [17, 18, 19, 20],
                [22, 23, 24, 25]])
column_sums = np.sum(mat, axis=0)

print(column_sums)

[51 54 57 60]


#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = np.array([[1, 2], [2, 3]])
B = np.array([[4, 5], [6, 7]])

# Multiply matrices A and B
result = np.dot(A, B)



print(result)







[[16 19]
 [26 31]]


####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:
import numpy as np

initial_array = np.array([[1.3, 2.5, 3.6, np.nan],
                           [2.6, 3.3, np.nan, 5.5],
                           [2.1, 3.2, 5.4, 6.5]])

column_means = np.nanmean(initial_array, axis=0)

initial_array[np.isnan(initial_array)] = column_means[np.isnan(initial_array)]

print(initial_array)

# You're done!